### ISSUE TITLE
Failed to build sample project

### ISSUE THREAD

**Issue by floatinghotpot** [flurry/YodelAndroidApp#1]
When build the sample project with either gradle CLI or eclipse, both failed.

Here is the log:
- What went wrong:
  Execution failed for task ':yodel-sample:processDebugResources'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  > /Users/liming/bin/android-sdks/build-tools/21.1.2/aapt package -f --no-crunch -I /Users/liming/bin/android-sdks/platforms/android-21/android.jar -M /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug -A /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/assets/debug -m -J /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/generated/source/r/debug -F /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/resources-debug.ap_ -G /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/proguard-rules/debug/aapt_rules.txt --debug-mode --custom-package com.yahoo.mobile.client.android.yodel -0 apk --output-text-symbols /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/symbols/debug
  > Error Code:
  >   1
  > Output:
  >   /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:477: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:480: error: Error: No resource found that matches the given name: attr 'colorAccent'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:478: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:479: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:481: error: Error: No resource found that matches the given name: attr 'searchViewStyle'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values-v21/values.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values-v21/values.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values-v21/values.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values-v21/values.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values-v21/values.xml:9: error: Error: No resource found that matches the given name: attr 'searchViewStyle'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:483: error: Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.SearchView'.
  
    /Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/build/intermediates/res/debug/values/values.xml:484: error: Error: No resource found that matches the given name: attr 'queryBackground'.

**Comment by ugonna** [comment]
You need to make sure you've downloaded the Support Libraries, particularly v4 and v7, for you Android SDK.

**Comment by floatinghotpot** [comment]
I run gradle build, and it failed with following error:

```
UnicMac:yodel-sample liming$ gradle build;

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/liming/workspace/3pp-sample/YodelAndroidApp/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'YodelAndroidApp'.
> Failed to apply plugin [id 'android-reporting']
   > A problem occurred configuring project ':yodel-sample'.
      > Could not resolve all dependencies for configuration ':yodel-sample:_debugCompile'.
         > Could not find com.android.support:cardview-v7:21.0.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/support/cardview-v7/21.0.3/cardview-v7-21.0.3.pom
               https://repo1.maven.org/maven2/com/android/support/cardview-v7/21.0.3/cardview-v7-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/cardview-v7-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/cardview-v7.jar
           Required by:
               YodelAndroidApp:yodel-sample:unspecified
         > Could not find com.android.support:support-v4:21.0.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
               https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/support-v4-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/support-v4.jar
           Required by:
               YodelAndroidApp:yodel-sample:unspecified
         > Could not find com.google.android.gms:play-services:6.5.87.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/google/android/gms/play-services/6.5.87/play-services-6.5.87.pom
               https://repo1.maven.org/maven2/com/google/android/gms/play-services/6.5.87/play-services-6.5.87.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/play-services-6.5.87.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/play-services.jar
           Required by:
               YodelAndroidApp:yodel-sample:unspecified
         > Could not find com.android.support:appcompat-v7:21.0.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.pom
               https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0.3/appcompat-v7-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/appcompat-v7-21.0.3.jar
               file:/Users/liming/workspace/3pp-sample/YodelAndroidApp/yodel-sample/libs/appcompat-v7.jar
           Required by:
               YodelAndroidApp:yodel-sample:unspecified
```

Then I copy the jars from android sdk to libs:
- google-play-services.jar
- android-support-v4.jar
- android-support-v7-appcompat.jar
- android-support-v7-cardview.jar

And also change to android 5.1.1, then build with eclipse, it then fails with lots of error messages related with resource in previous post .

**Comment by ugonna** [comment]
@floatinghotpot  If building with gradle CLI, you shouldn't use jar files in the libs folders unless you rewrite the [_build.gradle_](https://github.com/flurrydev/YodelAndroidApp/blob/93369462de30fa803068769b056b5fbb46511fe7/yodel-sample/build.gradle) file to reference those jars in your libs folder. 

You can fix your dependency issues by properly referencing your Android SDK that has those libraries.

**NOTE**: I also just noticed that you're using system-provided gradle. Please use the [gradle wrapper](https://github.com/flurrydev/YodelAndroidApp/blob/93369462de30fa803068769b056b5fbb46511fe7/gradlew) instead to build.

**Comment by ugonna** [comment]
I'll be closing this. Feel free to open another one or contact support@flurry.com if you have any other questions about the SDK.
