### ISSUE TITLE
How to use expandable ads?

### ISSUE THREAD

**Issue by RapsIn4** [flurry/YodelAndroidApp#4]
https://github.com/flurry/YodelAndroidApp/blob/master/yodel-sample/src/com/yahoo/mobile/client/android/yodel/NativeAdFetcher.java#L92

There's no integration with expandable ads.

https://developer.yahoo.com/flurry/docs/publisher/code/android/

How do I used these methods?

``` java
public void setExpandableTrackingView(View trackingView, View ctaView);

public void setCollapsableTrackingView(View trackingView, View collapseView);
```

I found this gist: http://codegists.com/snippet/java/flurryandroidnativepencillistenerjava_flurrydev_java

``` java
new FlurryAdNativeListener() {

    @Override
    public void onExpanded(FlurryAdNative adNative) {
            mExpandablePanel.setVisibility(View.VISIBLE);
            mExpandButton.setBackgroundDrawable(mUpArrowDrawable);
            adNative.setCollapsableTrackingView(mMainContainer, mCollapseButton);
    }

    @Override
    public void onCollapsed(FlurryAdNative adNative) {
            mExpandablePanel.setVisibility(View.GONE);
            mExpandButton.setBackgroundDrawable(mDownArrowDrawable);
            adNative.setExpandableTrackingView(mMainContainer, mMoreButton);
    }
}
```

It would be great if the example include something expandable ads.

Thanks!

**Comment by ugonna** [comment]
This repo serves as an intro to native ad integration, along with some best practices. You can find integration samples for expandable native ads and other ad types in the core [integration sample](https://github.com/flurry/android-AdIntegrationSamples/) repo.

For expandable ads in particular, take a look at how this [fragment](https://github.com/flurry/android-AdIntegrationSamples/blob/master/native/src/main/java/com/flurry/sample/gemini/StreamListViewFragment.java#L73-L87) supports both expandable native ads and regular native ads with the help of [this library](https://github.com/flurry/StreamAds-Android).
